### ISSUE TITLE
Wrong Spanish translations

### ISSUE THREAD

**Issue by RGB-es** [petrkle/tabulka#1]
Version 6.2 from Android Play Store.

The right Spanish translation for "Lead" is "Plomo," but in the app it reads "Chumbo," which is, AFAIK, the Brazilian-Portuguese name. (In Argentina and Uruguay, "chumbo" means "hand gun" while in the rest of Latin America "higo chumbo" refers to the prickly pears).

Also, there is an error for Erbio (Er) which is named in the app as Terbio (Tb).

Other errors: it should be

Astato instead of Ástato
Copernicio instead of Copernicium
Darmstadtio instead of Darmstadtium
Flerovio instead og Flerovium
Livermorio instead of Livermorium
Moscovio instead of Moscovium
Nihonio instead of Nihonium
Oganesón instead of Oganesson
Roentgenio instead of Roentgenium
Teneso instead of Tennessine

There are other differences. For example, in Spanish Volframio (or Wolframio) is preferred to Tungsteno and Yodo is more used than Iodo, even if both are considered correct. Check the wikipedia page for the Spanish element names: 

https://es.wikipedia.org/wiki/Elemento_qu%C3%ADmico

**Comment by petrkle** [comment]
Thanks.
Spanish translation is [updated](https://github.com/petrkle/tabulka/commit/6d8e9c3c2b34207fa412ac4148a9e6b1b8499e17).
