### ISSUE TITLE
Latest update from app-store makes app crash on start

### ISSUE THREAD

**Issue by RGB-es** [petrkle/tabulka#3]
[Android 11 on samsung galaxy A10, all updates applied]

After yesterday update, the app fails to launch. There is no error message, just starts to draw the UI and then close. If I insists on trying to open it, android just says "the app is still not running"

**Comment by petrkle** [comment]
Pull requests are welcome.

Hopefully fixed with [this change](https://github.com/petrkle/tabulka/commit/949268bfb31151e079eeef449c33e67429ff5604).
